name: avrodi_sharif
description: A new Flutter project.
publish_to: 'none'

version: 1.0.4

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI and theme
  cupertino_icons: ^1.0.8
  adaptive_theme: ^3.6.0
  flutter_bloc: ^9.0.0
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.10+1
  zoom_tap_animation: ^1.1.0
  arabic_font: ^0.0.9

  # Utilities
  url_launcher: ^6.3.1
  equatable: ^2.0.7
  get_it: ^8.0.0
  http: ^1.2.2
  path_provider: ^2.1.4
  hive: ^2.2.3

  # Firebase (latest stable, with new gRPC fix)
  firebase_core: ^3.5.0
  cloud_firestore: ^5.4.4

  # Tools
  rename: ^3.0.2
  icons_launcher: ^2.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

icons_launcher:
  image_path: "assets/images/app_logo.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true
